from ShapesStructure import TOTAL_SHAPES, ShapesStructure

MOVEMENT_PUNISHMENT = -1  #* 0.5
INVALID_MOVEMENT_PUNISHMENT = -10
INVALID_PLACEMENT_PUNISHMENT = -10
LOSE_PUNISHMENT = 0
REWARD_PLACEMENT = 10 * 5

STOP_ACTION = "STOP"
OPPONENT = 1
PLAYER = 0

